### ISSUE TITLE
Login with username only

### ISSUE THREAD

**Issue by piegamesde** [wireapp/wire-android#1880]
## The problem

My account is username only, I have not set any email address or phone number. On my phone, I cannot log in because it requires either an email or a number, which I don't have. The web app still works fine though.

## Environment

* Wire version that exhibits the issue: 3.21.661
* Android OS version used to run Wire: 7.1.2
* Is this a custom firmware or a stock one: Custom, LineageOS 14.1
* Mobile phone model/manufacturer: Samsung Galaxy S4 mini

## Screenshots

![image](https://user-images.githubusercontent.com/14054505/48899189-2ecfd680-ee4f-11e8-9019-2ac73ebbac47.png)

**Comment by marcoconti83** [comment]
Hi @piegamesde ,
thanks for the report. AFAIK the only way you can register an account without using an email or phone number is by using the single-sign-on feature, which we released in January, and your issue was opened before that. Can you clarify how you managed to register without using phone number or email? Which platform did you use? Thanks

**Comment by piegamesde** [comment]
Apparently, I *did* provide an email during registration (found one in my password manager) and forgot about it. The general issue remains though: I can login using my username instead of the mail on web, but not with the app.

**Comment by marcoconti83** [comment]
Thanks for checking @piegamesde , at least that mystery is solved :) 

I'll add the "feature request" label. The feature makes sense, but I'm not sure when we will have time to pick this up. If anyone in the community feels like trying to solve this before we have a chance to look at it ourselves, I believe this could be a good self-contained topic to make a contribution to the app. In that case, let me know and I can give some hints on where to start with the code.

**Comment by CyborgRahil** [comment]
@marcoconti83 
For implementing this its better to add one more TAB in login section with text username.

**Comment by Kartikkman** [comment]
Hi @marcoconti83  , I want to contribute for App . I am a beginner & this is my first time with this kind of thing . 

Should I proceed with this  issue ? 

Thank You

**Comment by marcoconti83** [comment]
Hi @Kartikkman ,
Everyone is welcome to contribute! 

Addressing this is a multi-step process.

0. Setup: check out and build the project, run a compiled version on your phone. See the README for instructions.
1. Make sure the input field accepts text that is not an email
1. Make sure the network layer does the right request for logging in with username instead of email (note: I believe the network layer already handles both, but I'm not 100% sure)
1. Change the suggestion to say "email or username" (@CyborgRahil I would use the same tab for now, it's simpler to start with, and we can always add another tab later)

Let me know when you are done with step 0, and I will give you some guidance for the following steps.

**Comment by Kartikkman** [comment]
Hi @marcoconti83  , Apologies for getting back on it after Long  . 

I am done with Step 0 ,  set up the Code & Tried the Compiled version of App . 

Can you please Guide me on further steps  ( Which File to Start Working upon  )??

Thank You

**Comment by Kartikkman** [comment]
@marcoconti83 ?? You there ? Waiting for Long for your reply ??

**Comment by marcoconti83** [comment]
Hi @Kartikkman ,
apologies for the delay, summer is a slow month in Europe :) 

In case this PR requires making changes to the underlying library "sync engine", did you manage also to compile the "[sync engine](https://github.com/wireapp/wire-android-sync-engine/)" and run a local version of the app using a locally compiled version of sync engine? If so, great!

I would start from [here](https://github.com/wireapp/wire-android/blob/develop/app/src/main/scala/com/waz/zclient/appentry/fragments/SignInFragment.scala#L111), there is an email validator for the field, that should be changed to a validator that accepts emails OR a handle. Internally, in the code we use the term "handle" for usernames. 

Handles can be between 2 and 21 characters long, alphanumeric and dash ("-") only, so the validator should reject anything that is not matching. You can find an example of handle validation [here](https://github.com/wireapp/wire-android/blob/develop/app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangeHandleFragment.scala#L260).
