### ISSUE TITLE
Images Not Respecting Orientation/Rotation (Portrait)

### ISSUE THREAD

**Issue by metal450** [wireapp/wire-android#2224]
In version 3.35.807 for Android, sending portrait-oriented photos does not show the proper orientation (they appear as landscape, both in the chat history and when viewed fullscreen).

I scrolled up to previous photo messages (sent in previous versions of the app), and this wasn't the case - they were displayed properly. So this appears to be a newly-introduced bug.

**Comment by Gardosen** [comment]
Hy,

thanks for reporting this to us. Could you please provide us some information about your device, so we can work on reproduction steps and identify the issue which effects you?

What Device do you use? E.G. Nexus 5, Galaxy S8, OnePlus 5
What AndroidOS is installed? E.G. 6.0.1, 7.0, 8.1
Is it a Stock ROM or Custom ROM? E.G. Original or something like Lineage, or AOSP
Is your Phone rooted?
Do you use a special Camera App or the native Camera provided by the system?

Looking forward to your response.

Kind regards
Marco

**Comment by metal450** [comment]
Device = Galaxy S9
Android Version = 9
ROM = https://forum.xda-developers.com/galaxy-s9/samsung-galaxy-s9--s9-cross-device-development/rom-u1arc5-devbase-v5-2-t3764822
Rooted
Native camera app (though I was sending an existing image that had previously been taken - and that is displayed with proper orientation in the gallery)

**Comment by Gardosen** [comment]
Hey, 

thanks for getting back to me about this.
I will start investigating this. in the mean time, could you provide a small video and some screenshots of the issue? it might help me to identify the issue faster.

Kind regards
Marco

**Comment by metal450** [comment]
1) Here's while selecting a photo (you can see that it's portrait): https://lnk2.tk/snaps/2019-07-24_10.42.17.png

2) Here's how it shows in the conversation (rotated incorrectly): https://lnk2.tk/snaps/2019-07-24_10.48.01.png

(Note, however, that I was really just briefly installing this build to test if the same blocking issue I've been reporting/waiting for for over a year has been resolved - that backing up locally excludes/omits assets, as discussed in #1688, #2090, & Zendesk #57840. As it seems to have still not been addressed, I'm unfortunately still not actually using Wire - I basically just install each update, test that issue, & when not fixed, I move on.  I noticed this new bug when testing that.)

**Comment by swrogers** [comment]
We are seeing the exact same issue on two other devices as well.

Devices: Oneplus 7 Pro / Galaxy S8

Android OS: 9 (Oxygen OS 9.5.9.GM31CB - TMobile Stock) / 9 (Samsung Stock)

Rooted: Neither

With my Oneplus 7 Pro, I'm seeing this behavior with both the stock camera and a Google Camera APK. The Samsung is also stock camera.  

I could post images as well, but they are basically identical to what metal450 posted above.

**Comment by Gardosen** [comment]
Hey @swrogers and @mental450,

Thank you very much for the detailed device information. I will try to reproduce these behavior on Monday and hopefully will be able to provide so d information to our devs so they can fix it. 

Kind regards
Marco

**Comment by kroerig** [comment]
I see this issue too.

**Comment by lupu** [comment]
Thanks for looking into this.

I'm also experiencing the issue on LG G4. It seem like exif Orientation is being ignored by the Android wire client when the picture is downsampled for upload into the conversation. A friend who's not hitting this issue seems to have a camera that rearranges pixel data to match orientation instead of setting it in exif headers. Here's an example photo you can use to reproduce the issue:
 http://juurela.net/wire_sample.jpg - Thumbs up: works correctly. Thumbs down: bug manifested.

When sharing this image in Wire (Android), the content is shown with correct orientation in the preview but it appears upside down in the conversation. The same image works correctly when uploaded from Web Client.

**Comment by Filbuntu** [comment]
I was reported that the issue happens on a Xiaomi Mi9.

**Comment by Bpiet84** [comment]
Same issue on Pixel 3a since about 3 weeks. Since about a week the pictures are sometimes shared twice. Already deleted files/cleared cache and reinstalled Wire.

**Comment by Filbuntu** [comment]
There was an update of the Wire app two days ago and it says:
[Fixed](https://play.google.com/store/apps/details?id=com.wire ):
- Some images where rotated when sending.
- Some devices had issues when sending photos taken with the in-app camera.

Hopefully this will help! Anybody experienced an improvement?

**Comment by Bpiet84** [comment]
Unfortunately the issue still exists. I have the current version 3.37.820 installed and just tested again - wrong rotation and the picture was sent twice.

**Comment by lupu** [comment]
The message in the update sounded promising but indeed the problem still persists. For Wire devs: the image I linked previously reproduces the issue. It's the original JPEG as produced by the LG G4 camera, using exif Orientation info instead of rearranging pixel data for rotated images.

**Comment by IronJunkie** [comment]
Ver 3.37.820 fixed it for me on Essential PH-1 Stock Android 9 Aug security patch

**Comment by IronJunkie** [comment]
Correction: issue is NOT fixed for me, well kinda is fixed but only for some contacts. I just msg another contact the same photo & it is rotated. Apparently the contact for whom it is fixed has a new phone, a Nokia A7 running Android 9 Pie (stock), she was previously on an old (about 4yrs) Samsung. Other contact for which picture rotates on send is on a Samsung Tab A (2018) stock Android 8 (I believe), she has automatic app updates on so should be up to date.

**Comment by kroerig** [comment]
I can also confirm that this issue hasn't been fixed in 3.37.820 yet.
Phone: Sony Xperia ZX1c
Android: 9

Pictures taken with Sony camera app.

**Comment by kroerig** [comment]
Any news on this? Images still get rotated.

**Comment by lupu** [comment]
This bug is very simple to reproduce on any Android device: attach the image I linked in my previous comment into the Wire discussion on any Android device. Is there anything else I can provide to help solve the issue?

**Comment by kroerig** [comment]
What I noticed is that if you share the picture though attach file or from another app, it get's rotated. If you use integrated camera function, it doesn't.

**Comment by lupu** [comment]
So EXIF image rotation is not honored when using Android's native Share mechanism and selecting Wire as the sharing method. The same image file works properly when attached using the camera icon under a conversation in Wire, as mentioned by kroerig.

**Comment by Dashon1** [comment]
I'm also experiencing this problem on one plus 7 pro. Sending one at a time works just fine but trying to send multiple photos as attachments or via android's native share rotates all photos.

**Comment by luciusbono** [comment]
I'm also experiencing this issue. Happy to provide whatever details are helpful.

**Comment by mstefany** [comment]
I'm also experiencing the same issue. Samsung Galaxy S7, latest stock ROM, latest Wire for Android.

**Comment by makingthematrix** [comment]
A possible fix will be included in the next release (3.46):
https://github.com/wireapp/wire-android/pull/2609

**Comment by Filbuntu** [comment]
Thanks a lot for the fix. It seems the recent Android Wire update worked to fix it on a Xiaomi Mi9.
