### ISSUE TITLE
Unconsensual read receipts

### ISSUE THREAD

**Issue by Wurzelkoch** [wireapp/wire-android#2305]
**Describe the bug**
In one of my chats I every now and then get read receipts while that person says they have read receipts turned off.
Yesterday it happened like this:
1. I sent some messages. They didn't get a "delivered" tag.
2. Chat partner answered to these messages.
3. I send more messages and don't get more answers
4. Hours later I get "read receipts" for messages from 1 and 3, all with the same timestamp.
Person says to have read receipts turned off.
5. For later messages today receipts are received like expected (only delivery receipts in time)

**Expected behavior**
Delivery receipts to be received in time, no read receipts

**Smartphone (please complete the following information):**
- Wire version that exhibits the issue: 3.27.697
- Last Wire version that did not exhibit the issue (if applicable):
- Android OS version used to run Wire: 7.0. kernel 3.18.35+ build 010 08
- Is this a custom firmware or a stock one:
- Mobile phone model/manufacturer: alcatel 4047D
- Mobile network type (EDGE/LTE/Wi-Fi/Offline): 

**Additional context**
I can't see those unconsensual read receipts on the desktop app, only on android. Consensual read receipts I see on both devices.

**Comment by marcoconti83** [comment]
Hi @Wurzelkoch ,

thanks for the report, could you clarify what platform is your chat partner using? And is this a direct conversation (also called 1:1) or a group chat?

**Comment by marcoconti83** [comment]
This is being addressed in https://github.com/wireapp/wire-android/pull/2396

**Comment by makingthematrix** [comment]
The PR which addressed this issue was merged and is available in public. Is the problem still happening?
