### ISSUE TITLE
Wire App is not available in Google Play

### ISSUE THREAD

**Issue by victormhg** [wireapp/wire-android#3627]
As of today, we can't find the Wire App in the Google Play Store.
It's a temporary problem?

**Comment by TrySend** [comment]
I also have this question.I can't install Wire on my new phone now-there is no Wire in Google Play Store and dow load from official site is not availible.When this problem will be sold?

**Comment by mrickma** [comment]
Same problem here (Germany). I installed from F-Droid.

**Comment by makingthematrix** [comment]
@victormhg , @TrySend , @mrickma : Hi there. All fixed now.

**Comment by FritzJo** [comment]
Sorry to re-open this issue, but it seems that this problem still exists
https://play.google.com/store/apps/details?id=com.wire currently shows ```We're sorry, the requested URL was not found on this server.```

**Comment by victormhg** [comment]
I also confirm that Wire App is not available on Google Play.
(tested from Spain)

![wire-not-found](https://user-images.githubusercontent.com/21988790/147342658-73db1e6b-4f86-47df-82b8-fb1830bbc3e1.jpg)
