### ISSUE TITLE
No images are able to load.

### ISSUE THREAD

**Issue by KyleGospo** [wireapp/wire-android#760]
I'm experiencing an issue where no images can be loaded. This includes my own contact photo, others contact photos (Including the Anna chat bot), images I sent from another device, and any photo someone sends directly to me. The loading bar never appears and attempting to save the blank images results in a cannot be saved error.

Setting my own personal contact photo via the app allows that one and only image to work, however if I uninstall and reinstall Wire it will fail to load once more. Additionally any images sent from this device work fine. Images also don't appear to load for URL previews, and the yellow no connection message flashes briefly when opening the app.

I have already sent a log to support. The device is a stock Google Pixel on Android 7.1.2 beta.

Note: Other devices on this account (A windows native app and a web login) both work perfectly. It is only my Pixel that I initially set this account up that is affected. Additionally, the person I am attempting to chat with is using a Google Pixel on Android 7.1.1 without issue.

**Comment by KyleGospo** [comment]
Issue still present in 2.31.324

**Comment by jimsth** [comment]
I had a similar issue and it was caused by the beta version of Google Play Services (10.5.x). Reverted back to 10.2.99 and the issue was fixed.
Now why the app is so dependent on GMS it`s another topic

**Comment by DavyLandman** [comment]
I too on cm 13 (Android 6.0.1) with Google play services 10.5.48 am experiencing this issue.

**Comment by DavyLandman** [comment]
a picture that I send on desktop also doesn't show on my phone. so it only is my own device uploaded pictures that work.

**Comment by DavyLandman** [comment]
```logcat
04-11 11:12:14.479  1359  5604 W System.err: javax.net.ssl.SSLException: encrypted packet oversized
04-11 11:12:14.479  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:496)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:458)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:423)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
04-11 11:12:14.479  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
04-11 11:12:14.703  1359  5604 W System.err: javax.net.ssl.SSLException: encrypted packet oversized
04-11 11:12:14.703  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:496)
04-11 11:12:14.703  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:458)
04-11 11:12:14.703  1359  5604 W System.err: 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:423)
04-11 11:12:14.703  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
04-11 11:12:14.703  1359  5604 W System.err: 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
04-11 11:12:14.704  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
04-11 11:12:14.704  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
04-11 11:12:14.704  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
04-11 11:12:14.704  1359  5604 W System.err: 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
```

I've captured a logcat while wire got a message with a picture, not a lot of detail there, but did notice this exception being printer to the stderr stream, might be related?

**Comment by DavyLandman** [comment]
going back to 10.2.99 google play services also fixed it for me.

**Comment by TubaOrNotTuba** [comment]
I've reverted to 10.2.98, the only build offered to me.  I'm waiting to test the "fix"; however, in the meantime Wire needs to understand this "fix" is unacceptable.  When one is forced to revert Google Play Services to a previous version EVERY SINGLE APP and DEVICE that relies on it is reset and have to be re-setup.  This includes Android Wear, Android Pay, and Android Auto.  I'm not saying don't apply the fix, but everyone needs to be aware of the pitfalls of doing so.

**Comment by TubaOrNotTuba** [comment]
I've reverted to 10.2.98, the only build offered to me. The "fix" works; however, Wire needs to make sure every user it suggests roll back understands this "fix" can be really problematic. When one is forced to revert Google Play Services to a previous version EVERY SINGLE APP and DEVICE that relies on it is reset and have to be re-setup. This includes Android Wear, Android Pay, and Android Auto. I'm not saying don't apply the fix, but everyone needs to be aware of the pitfalls of doing so.

**Comment by ConorIA** [comment]
This is really a huge usability issue for me. I don't have the option of reverting Google Play Services without tracking down an old OpenGApps package. I'm not willing to risk a full reinstall of my apps over this. 

I haven't noticed anyone else mention audio messages, but I can receive neither audio messages or images form my SO. At first I thought it was a permissions error, but I've given Wire full permissions across the board (which makes me wonder: why does Wire ask to write SMS?)

Some screens:

- [Audio messages fail and do not download](https://cloud.conr.ca/s/7mYAdkCL5YTX9zX)
- [Images appear as blank boxes](https://cloud.conr.ca/s/02la3IZuvDfAdaW)
- [Wire has full permissions](https://cloud.conr.ca/s/sraEbWgEqFajIOb)
- Wire has been allowed in Privacy Guard: [1](https://cloud.conr.ca/s/lj9L9lSDeAeff4D), [2](https://cloud.conr.ca/s/p2Ks5vbsbzaINGd)
- [Puppy tax!](https://cloud.conr.ca/s/7KPFoNlMWETigLE) This image was sent over Wire (one of those black boxes), it works fine on my laptop, but not on my phone.  

If I send an image to myself (i.e. a group with all other members removed) on my phone, I get the image fine. If I send from my laptop, I do not. I'm happy to try and debug with a little guidance!

**Comment by TubaOrNotTuba** [comment]
Conor, why can't you revert to the released version of GPS?  All you have to do is disable system admin rights for GPS and you'll be allowed to uninstall the beta build you're running and it'll revert to an older version.  Then launch Wire and it'll upgrade it to 10.2.98 or 10.2.99 depending on the device.  The issues we've been having are part of the caveats of running beta builds of other products, especially system-level products.

**Comment by ConorIA** [comment]
@TubaOrNotTuba, I've recently reinstalled LineageOS with OpenGapps. The included version of GPS is 10.5.48. It isn't an "update", but is the base APK installed into `/system`. I tried uninstalling GPS via Titanium backup, and installing a past version from APK mirror, but it gave me all sorts of "corrupt package" errors (wouldn't install) and force close errors. As far as I can tell, my only option would be to download an old OpenGapps package (10.2.98 is included in the packages form February or March) and wipe my `/system` before installing. I'm not sure, but I expect that this will give me issues if I don't wipe data for all of my Google Apps. That being said, this issue has only surfaced since I re-installed everything last week, so I expect GPS later than 10.2.99 ought to work, but am wary of trying to revert.

**Comment by TubaOrNotTuba** [comment]
Just not sure Wire should be focused on non-official Android builds when the vast majority of their users are running official builds.  If LineageOS is going to include beta builds of GPS that's on them.  When one runs a non-official version you get what you get.  Revert to the real OS and your problems are solved.

**Comment by ConorIA** [comment]
I understand that Wire can't support all non-official ROMs, but LineageOS-specific features like privacy guard are well within the realm of Wire's privacy and user-protection philosophy. Anyway, we're getting a little off topic. I wasn't demanding a fix, just providing the information and I have offering a little debugging (with guidance). I hadn't actually realized that GPS above 10.2 was in beta. Shame OpenGapps doesn't make it easier to run only the latest stable versions.

**Comment by Gregory-K** [comment]
Same problem here running on a rooted (locked bootloader) sony z3 compact.

Tried in various combinations:
* Clear Cache (wire and google play services).
* Clear Data (wire and google play services).
* Remove all Wire devices, uninstall - re-install.
* Install latest beta google play services.

None of the above solved the problem.

What worked:
1. Remove all google play services updates. Clear Cache.
2. Open Wire and wait for images to sync (I don't know if this step is mandatory).
3. Update to latest google play services via play store (in my case 10.5.56)
4. Open Wire (and everything seems to be working again).

**Comment by Gregory-K** [comment]
Same problem here running on a rooted (locked bootloader) sony z3 compact.

For a moment I thought that reinstalling (back to ROM’s version and update) the latest google play services was the solution, but not, it was late night hours and a matter of cache kept alive 😊

The only solution, so far, is reverting to gps version 10.2.98.

I didn’t check any other version between 10.2.98 and 10.5.55. Google play “beta tester” gives you 10.5.56. Out of the beta program you have 10.5.55.

@TubaOrNotTuba I don’t know if and how much the rooting procedure can cause a problem like this, but I have an official rom that updates, for the time speaking, to 10.5.55.
So, there is a big possibility that all Sony Z3C out there, properly updated, cannot run Wire. I am saying “cannot” because plain users just blame the apps or their phone as “not working”.

**Comment by TubaOrNotTuba** [comment]
On every device I've tried gotten 10.2.98 or 10.2.99.  I've not tried a Sony. To get there I just reverted to the base GPS from the beta and fired up Wire - it sent me to GPS in the Play Store.  On each device I've tried it pulled a version that worked with Wire.   

In the end, however, Wire is going to have to either be MUCH faster with updates, especially if they ever want to be a business-level platform, for GPS or they need to not be using GPS for image/media display if they can't keep up.  Clearly other apps, even full end-to-end encrypted ones, are handling this fine. Whatsapp and Wickr both work like a champ.

**Comment by kujaw** [comment]
I had the same issue on Android 7.1.2 and GPS 10.5.48, rom: Optimized LineageOS 14.1. 
I tried to install earlier version of GPS but received error so I didn't install it. I went to app settings and clicked on "Deactivate" while in GPS app settings. After that I'm able to load received images.

**Comment by luciusbono** [comment]
I am also having this issue on LineageOS on GPS 10.5.48. The odd thing is that images used to mostly work a few days ago but have basically stopped as of today and yesterday.

This is almost certainly unhelpful but: bringing up the Search pane in the conversation will display the loading icon on images that appear blank. I also found that a few images that had previously been blank appeared yesterday when I opened the conversation in the MacOS client on another device. 

Happy to test anything that might help the devs. I'm interested in trying work arounds but I'm more interested in helping the devs secure a long term fix even if I have to wait.

**Comment by TubaOrNotTuba** [comment]
It's absolutely 10.5.xx that's the problem.  Roll back to 10.2.9x and your problem will disappear.

**Comment by luciusbono** [comment]
@TubaOrNotTuba thanks for confirming! I may go that route but it seems like reverting the GPS won't really help the Wire devs get to the root cause of the issue - but if 10.5.x is enough of a corner case that the devs are unconcerned I'll happily revert.

**Comment by luciusbono** [comment]
Wanted to come back and confirm: I was able to revert to GPS 10.2.99 by doing the following: 

1. Boot to recovery
2. use `adb` to push the latest version of LineageOS to my device as well as [this gapps](https://github.com/opengapps/arm/releases/download/20170304/open_gapps-arm-7.1-nano-20170304.zip) package
3. Wipe the /system partition
4. Install LineageOS and the gapps package and reboot

Wire worked perfectly, as have all my other apps so far. 

I did have to reboot one more time to clear up some notification tray weirdness but I believe that is a totally unrelated issue. 

My phone is full-disk encrypted, in case anyone else is in that boat.

**Comment by TubaOrNotTuba** [comment]
I've spoken with a Wire rep and they're definitely concerned and are working on a fix.

**Comment by MrCustomizer** [comment]
Possible duplicate: #830
Possibly related: #826

**Comment by cliffTifflor** [comment]
I can confirm this problem, it's still present with newest LineageOS and newest gapps. 
Just flashing the gaaps @luciusbono has linked has fixed the issue. There was no need to reinstall LineageOS.

**Comment by andr-d** [comment]
The issue is fixed for me with the latest wire version 2.32.330 (the one with the  new chat list). Using Play services version 10.5.62.

**Comment by IronJunkie** [comment]
The update hasn't fixed it for me, I'm using Google Play Ser ver 11.0.38. On Android 7.1.2

**Comment by deanrobertcook** [comment]
For the more tech-savie users out there who want to know what's going on:

According to official sources, It seems as though all versions of play services beyond [10.2.4](https://developers.google.com/android/guides/releases) are beta versions. Currently, our HTTP client library [Async Android](https://github.com/koush/AndroidAsync) uses parts of the play services framework (if available) as part of it's SSL magic and on just about any beta version, it crashes. 

It seems as thought the Google team [have fixed the bug](https://github.com/google/conscrypt/issues/76), but it's not very clear to me when that fix will be released or even if it already has and the bug still persists. Hopefully I'll have more information from them soon.

It's not much of a comfort to users experiencing the problem, but we'll be following this issue closely and make sure we update anything necessary as soon as it's available to us. If you're able to downgrade back to the latest official play services, that should fix the issue as far as I'm aware.

**Comment by KyleGospo** [comment]
This is now also broken on the Android O beta without using a beta version of Google Play Services.

**Comment by red-avtovo** [comment]
@KyleGospo could you provide the log from your device? Is it the same as [this one](https://github.com/wireapp/wire-android/issues/760#issuecomment-293199569)?

**Comment by KyleGospo** [comment]
@red-avtovo 
```
05-18 12:04:37.818 W/System.err(23740): javax.net.ssl.SSLException: encrypted packet oversized
05-18 12:04:37.818 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:496)
05-18 12:04:37.818 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:458)
05-18 12:04:37.818 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:423)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
05-18 12:04:37.818 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
05-18 12:04:39.292 W/System.err(23740): javax.net.ssl.SSLException: encrypted packet oversized
05-18 12:04:39.292 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:496)
05-18 12:04:39.292 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:458)
05-18 12:04:39.292 W/System.err(23740): 	at com.google.android.gms.org.conscrypt.OpenSSLEngineImpl.unwrap(:com.google.android.gms:423)
05-18 12:04:39.292 W/System.err(23740): 	at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:194)
05-18 12:04:39.292 W/System.err(23740): 	at com.koushikdutta.async.Util.emitAllData(Util.java:23)
05-18 12:04:39.292 W/System.err(23740): 	at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
05-18 12:04:39.292 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
05-18 12:04:39.292 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
05-18 12:04:39.293 W/System.err(23740): 	at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)
```

**Comment by IronJunkie** [comment]
I signed up to the Beta channel  for GPS in the hope that it would fix the issue and my ver changed from 11.0.38 up to 11.0.47 but it's not fixed. Running LinageOS 7.1.2

**Comment by darkbluelight** [comment]
I would wish for Wire to stop being dependend on Google Services. Google and privacy don't fit at all. On 4.1+ devices pictures don't load because Wire didn't implement a fix for TLS 1.2 functionality. See #870.

**Comment by Hyr0n** [comment]
My thoughts on the situation... I was pointed here and recommended by support to roll back and "not use beta" google services. But i was never on Beta. Im on the official release line with my Pixel XL and Pixel C tablet (as is many others i communicate with). This isnt "beta" google services anymore. Its an official release as of a month ago. Its been two months since the issue first appeared (for those actually using beta) and now its the direction google is going?

I want to keep using Wire, but not having images is a serious drawback. Is there any feedback from Google to the Wire devs that this will be pushed out and fixed? I dont want to change messaging apps, but we cant really go another month or two with text only. Thoughts?

**Comment by iddno** [comment]
For me it is that I can receive images etc. And see them. But on a friend's Huawei P8 device with Android 6 my sent images are not shown on this device. 

I am using latest lineageOS version (android 7.1.2) on my HTC 10 without any Google stuff, no Google play services etc. 

It's really a bummer, because I actually start to like this app.

**Comment by danielmanesku** [comment]
I am experiencing this issue since a couple of days ago on OnePlus X with default OS.

Google Play services is at version 11.0.55 at the moment.

**Comment by kylgry** [comment]
I have also been experiencing this issue for several weeks on a stock google pixel, running android 7.1.2 and google play services 11.0.55.

**Comment by bjoernherbig** [comment]
Thank you for reporting and sorry for the inconveniences. We are currently testing a fix for this and hope to roll it out soon.

**Comment by bjoernherbig** [comment]
We just released the fix with version 2.33.336. Thanks for your patience on this one!

**Comment by peti** [comment]
For what it's worth, version 2.33.336 makes no difference for me (Samsung S5 Mini, LTE, Lineage OS 14.1). Media messages I received still don't work. I can see they are there, but I cannot display or play any of them. It works in the web app, though.

**Comment by danielmanesku** [comment]
Just updated, works for me (stock OnePlus X). Thank you!

**Comment by red-avtovo** [comment]
@peti what version of Google Play Services are you using?

**Comment by kylgry** [comment]
2.33.336 has fixed the issue for me. Awesome!

**Comment by peti** [comment]
@red-avtovo, I was using version Google Play Services version 10.5.62, and that did not work. Now, I just flashed a new version of openGApps which includes GPS version 11.0.55. I'm glad to say that with the new version the Wire client works fine. I can see images and play video and audio messages. Thank you very much for your efforts!

**Comment by IronJunkie** [comment]
Yes, latest update fixed for me too running gps 11 & LinageOS 14.1.2.
Thanks devs!
