### ISSUE TITLE
Issues with opening wire from quick reply

### ISSUE THREAD

**Issue by someoneEsle** [wireapp/wire-android#775]
There are two issues with quick replies at the moment. (Nexus 5X, Android 7+, wire 2.31.324).

- receive a notification from A
- tap reply
- don't write anything, tap "Open Wire"
- you just sent an empty message to A

other issue:
- receive a notification from A
- tap reply
- write something, but don't send. Instead, tap "Open Wire"
- the message you typed has been sent. I would expect that "opening wire" takes the user to the conversation view and prefills the text field with whatever had been typed in the quick reply view.

**Comment by mykola-mokhnach** [comment]
The issue has been confirmed and reported to the bugtracker. Thanks for the detailed description.

**Comment by prt2121** [comment]
I believe these were fixed by my PR #806?
I don't know your internal process but shouldn't the issue be closed?

**Comment by someoneEsle** [comment]
That is correct, both issues have been fixed.

**Comment by prt2121** [comment]
awesome. thanks

**Comment by selurvedu** [comment]
>  receive a notification from A
>  tap reply
>  don't write anything, tap "Open Wire"
>  you just sent an empty message to A

The problem is still present with the latest version of Wire Android.
@marcoconti83
